// home-lang.js — the homepage's UI strings in English, 中文 and Bahasa Malaysia.
// English values copy the authored HTML exactly (so re-applying English never
// changes the page). Nodes carry data-i18n / data-i18n-html / data-i18n-ph /
// data-i18n-aria pointing at keys below; home.js applies them, and reviews.js
// reads its own dynamic strings (rv_*) through pick() for the current language.
//
// The baker reviews these phrasings — food names stay recognisable across
// languages, and the tone is warm and simple for a family bakery.

const en = {
  title: "Jien Luv 2 Bake — Small Batch Bakery",

  // Nav + language switch
  navBakes: "OUR BAKES",
  navOrder: "HOW TO ORDER",
  navCollection: "COLLECTION",
  navReviews: "REVIEWS",
  navContact: "CONTACT",

  // Hero
  heroKicker: "SMALL BATCH BAKERY",
  heroScript: "Freshly baked. Made with love. ♡",
  heroCopy: "Handcrafted bakes made in small batches, with quality ingredients and lots of care. Pre-order your favorites online for the next baking day.",
  ctaOrder: "ORDER ONLINE",

  // Our bakes
  bakesTitle: "OUR BAKES",
  bakesSub: "Fresh from our little kitchen — available for pre-order in limited quantities.",
  p1Name: "FOCACCIA",
  p1Size: "12\" × 9\"",
  p1Desc: "Soft on the inside, golden on the outside. Perfect on its own or with your favorite fillings.",
  p2Name: "ITALIAN PESTO HAM",
  p2Desc: "Ham • Pesto • Mozzarella<br>Tomato • Arugula<br>Parmesan<br><br>A fresh &amp; flavorful focaccia sandwich with the perfect balance of herby, cheesy &amp; savory.",
  p3Name: "CROISSANT",
  p3Desc: "Buttery, flaky and perfectly baked to golden perfection.",
  p4Name: "MUSHROOM & EGG",
  p4Desc: "Scrambled Egg • Mushroom<br>Caramelised Onion<br>Mozzarella • Arugula • Pesto<br><br>Hearty, wholesome and full of delicious comfort in every bite.",
  p5Name: "VEGETARIAN PIE",
  p5Desc: "Golden pastry filled with a delicious mix of vegetables. Comfort food at its best.",
  soon: "COMING SOON",

  // Notice boxes
  n1Title: "PRE-ORDER ONLY",
  n1Line: "Orders close at <strong>6:00PM</strong><br>the day before baking day.",
  n1Small: "Limited quantities available. Pre-order recommended.",
  n2Title: "MADE WITH LOVE ♡",
  n2Line: "Thank you for supporting our small home bakery.",
  n2Em: "You bake our day! ♡",

  // How to order
  oTitle: "HOW TO ORDER",
  oSub: "Simple, easy and confirmed upon payment.",
  s1t: "CHOOSE BAKE DAY",
  s1d: "Tue / Thu / Sat",
  s2t: "CHOOSE YOUR ITEMS",
  s2d: "Select your favorites",
  s3t: "TELL US YOUR QUANTITY",
  s3d: "Let us know how many",
  s4t: "CHOOSE COLLECTION OR DELIVERY",
  s4d: "SG Ara or Penang Island",
  s5t: "CONFIRM & MAKE PAYMENT",
  s5d: "Order confirmed upon payment ♡",

  // Collection & delivery
  iTitle: "COLLECTION & DELIVERY",
  selfTitle: "SELF COLLECTION",
  selfBody: "We will notify you when your order is ready for pick up.",
  deliTitle: "DELIVERY",
  deliArea: "LALAMOVE DELIVERY — PENANG ISLAND",
  deliBody: "Delivery fee is borne by customer. We pack with care for a safe delivery.",

  // Reviews
  rvTitle: "WHAT CUSTOMERS SAY",
  rvSub: "Real words from real bakes — reviews are welcome in English, Mandarin (中文) or Bahasa Malaysia.",
  rvFormTitle: "LEAVE A REVIEW",
  rvNote: "Tried something from Jien Luv 2 Bake? Tell us how it was.",
  nameLabel: "Your name",
  namePh: "e.g. Aisyah",
  ratingLabel: "Your rating",
  rvStarsAria: "Star rating, 1 to 5",
  rvStar1: "1 star",
  rvStar2: "2 stars",
  rvStar3: "3 stars",
  rvStar4: "4 stars",
  rvStar5: "5 stars",
  msgLabel: "Your review",
  msgPh: "How was your bake? What did you love?",
  msgNote: "Write in whichever language you are comfortable with — English, Mandarin or Bahasa Malaysia.",
  langLabel: "Review language",
  photoLabel: "Add a photo (optional)",
  photoTake: "Take photo",
  photoChoose: "Choose photo",
  rvPhotoAlt: "Your photo",
  rvSubmit: "SEND REVIEW",
  rvSending: "Sending…",
  rvErrFields: "Please add your name, a star rating (1–5) and a short review (up to 400 characters).",
  rvTooBig: "That photo is too large — please choose a picture under 25 MB.",
  rvErrSend: "Something went wrong sending your review. Please check your connection and try again.",
  rvEmpty: "No reviews yet — be the first!",
  rvPrevAria: "Previous review",
  rvNextAria: "Next review",
  rvThanksMain: "Thank you — your review and photo reached the baker. Every review is read personally and appears on this page once it is approved, usually within a day or two.",
  rvThanksHonest: "Honest reviews help other customers choose well — thank you for sharing it.",

  // Footer + developer line
  fConnectTitle: "LET'S STAY CONNECTED ♡",
  fTag: "Jien Luv 2 Bake<br>Small Batch. Big Love.",
  fWhatsappTitle: "WHATSAPP / ORDER",
  fInstaTitle: "FOLLOW US ON INSTAGRAM",
  devBy: "Website by",
};

const zh = {
  title: "Jien Luv 2 Bake — 小批量烘焙坊",

  navBakes: "我们的烘焙",
  navOrder: "如何订购",
  navCollection: "取货与派送",
  navReviews: "顾客评价",
  navContact: "联系我们",

  heroKicker: "小批量烘焙坊",
  heroScript: "新鲜出炉。用心手作。♡",
  heroCopy: "小批量精心手作的烘焙，挑选优质食材，倾注满满心意。想吃的，欢迎在线预订下一次烘焙日。",
  ctaOrder: "立即下单",

  bakesTitle: "我们的烘焙",
  bakesSub: "新鲜出炉、限量供应 — 欢迎提前预订。",
  p1Name: "意大利佛卡夏",
  p1Size: "12\" × 9\"",
  p1Desc: "外皮金黄，内里松软。单吃美味，搭配你喜欢的馅料也刚刚好。",
  p2Name: "意式香蒜火腿三明治",
  p2Desc: "火腿 • 香蒜酱 • 莫扎里拉芝士<br>番茄 • 芝麻菜<br>帕玛森芝士<br><br>新鲜又风味十足的佛卡夏三明治，香草、芝士与咸香之间平衡得恰到好处。",
  p3Name: "牛角包",
  p3Desc: "黄油香气十足，层层酥脆，烤至金黄完美。",
  p4Name: "蘑菇鸡蛋三明治",
  p4Desc: "炒蛋 • 蘑菇<br>焦糖洋葱<br>莫扎里拉 • 芝麻菜 • 香蒜酱<br><br>丰盛健康，每一口都充满温暖满足的幸福感。",
  p5Name: "素食派",
  p5Desc: "金黄的酥皮包裹着美味多样的蔬菜馅料，是最抚慰人心的经典美食。",
  soon: "即将推出",

  n1Title: "仅限预订",
  n1Line: "请在烘焙日前一天<br>晚上 <strong>6:00PM</strong> 前下单。",
  n1Small: "数量有限，建议尽早预订。",
  n2Title: "用心制作 ♡",
  n2Line: "感谢您支持我们的家庭小烘焙坊。",
  n2Em: "有您，我们的每一天都更甜！♡",

  oTitle: "如何订购",
  oSub: "简单轻松，付款后即确认订单。",
  s1t: "选择烘焙日",
  s1d: "周二 / 周四 / 周六",
  s2t: "选择心仪商品",
  s2d: "挑选你最喜欢的",
  s3t: "告诉我们数量",
  s3d: "让我们知道你要几份",
  s4t: "选择自取或派送",
  s4d: "SG Ara 或槟岛",
  s5t: "确认并付款",
  s5d: "付款后订单即确认 ♡",

  iTitle: "取货与派送",
  selfTitle: "自取",
  selfBody: "订单准备好后，我们会通知你来取。",
  deliTitle: "派送",
  deliArea: "LALAMOVE 派送 — 槟岛",
  deliBody: "派送费由顾客承担。我们会细心打包，确保安全送达。",

  rvTitle: "顾客怎么说",
  rvSub: "真实顾客的真实评价 — 欢迎使用英语、中文或马来文书写。",
  rvFormTitle: "写个评价",
  rvNote: "尝过 Jien Luv 2 Bake 的烘焙吗？跟我们说说你的感受吧。",
  nameLabel: "你的名字",
  namePh: "例如：Aisyah",
  ratingLabel: "你的评分",
  rvStarsAria: "星级评分，1 至 5",
  rvStar1: "1 星",
  rvStar2: "2 星",
  rvStar3: "3 星",
  rvStar4: "4 星",
  rvStar5: "5 星",
  msgLabel: "你的评价",
  msgPh: "烘焙味道如何？你最喜欢什么？",
  msgNote: "用你最舒服的语言书写即可 — 英语、中文或马来文都可以。",
  langLabel: "评价语言",
  photoLabel: "添加照片（可选）",
  photoTake: "拍照",
  photoChoose: "选择照片",
  rvPhotoAlt: "你的照片",
  rvSubmit: "发送评价",
  rvSending: "发送中…",
  rvErrFields: "请填写你的名字、星级评分（1–5 星）和一段简短评价（400 字以内）。",
  rvTooBig: "照片太大了 — 请选择 25 MB 以内的图片。",
  rvErrSend: "发送评价时出了点问题，请检查网络后再试一次。",
  rvEmpty: "还没有评价 — 来当第一个吧！",
  rvPrevAria: "上一条评价",
  rvNextAria: "下一条评价",
  rvThanksMain: "谢谢！你的评价和照片已经送到烘焙师手上。每一则评价都会被亲自阅读，审核通过后就会出现在这一页，通常一两天内就能看到。",
  rvThanksHonest: "真诚的评价能帮助其他顾客做出更好的选择 — 谢谢你的坦诚分享。",

  fConnectTitle: "保持联系 ♡",
  fTag: "Jien Luv 2 Bake<br>小批量制作 · 满满的爱",
  fWhatsappTitle: "WHATSAPP / 下单",
  fInstaTitle: "在 Instagram 关注我们",
  devBy: "网站制作：",
};

const ms = {
  title: "Jien Luv 2 Bake — Bakeri Skala Kecil",

  navBakes: "SAJIAN KAMI",
  navOrder: "CARA MENEMPAH",
  navCollection: "PENGAMBILAN & PENGHANTARAN",
  navReviews: "ULASAN",
  navContact: "HUBUNGI KAMI",

  heroKicker: "BAKERI SKALA KECIL",
  heroScript: "Baru dibakar. Dibuat dengan penuh kasih. ♡",
  heroCopy: "Bakaran kraftangan dalam kuantiti kecil, dengan bahan berkualiti dan penuh teliti. Tempah dalam talian untuk hari pembakaran yang seterusnya.",
  ctaOrder: "TEMPAH DALAM TALIAN",

  bakesTitle: "SAJIAN KAMI",
  bakesSub: "Terus dari dapur kecil kami — boleh ditempah awal dalam kuantiti terhad.",
  p1Name: "FOCACCIA",
  p1Size: "12\" × 9\"",
  p1Desc: "Lembut di dalam, keemasan di luar. Sedap dimakan begitu sahaja atau bersama inti kegemaran anda.",
  p2Name: "SANDWICH HAM PESTO ITALIA",
  p2Desc: "Ham • Pesto • Mozzarella<br>Tomato • Arugula<br>Parmesan<br><br>Sandwic focaccia yang segar dan penuh rasa — keseimbangan herba, keju dan masin yang sempurna.",
  p3Name: "CROISSANT",
  p3Desc: "Berminyak mentega, berkelopak halus dan dibakar hingga keemasan.",
  p4Name: "SANDWICH CENDAWAN & TELUR",
  p4Desc: "Telur • Cendawan<br>Bawang karamel<br>Mozzarella • Arugula • Pesto<br><br>Mengenyangkan dan menyihatkan — selesa dan puas pada setiap gigitan.",
  p5Name: "PAI VEGETARIAN",
  p5Desc: "Pastri keemasan dengan inti sayur-sayuran yang lazat. Makanan yang paling menenangkan.",
  soon: "SEGERA HADIR",

  n1Title: "TEMPOHAN SAHAJA",
  n1Line: "Tempahan ditutup pada <strong>6:00PM</strong><br>sehari sebelum hari pembakaran.",
  n1Small: "Kuantiti terhad. Tempahan awal disyorkan.",
  n2Title: "DIBUAT DENGAN KASIH ♡",
  n2Line: "Terima kasih kerana menyokong bakeri kecil kami.",
  n2Em: "Anda yang menceriakan hari kami! ♡",

  oTitle: "CARA MENEMPAH",
  oSub: "Mudah, ringkas dan disahkan selepas pembayaran.",
  s1t: "PILIH HARI BAKAR",
  s1d: "Selasa / Khamis / Sabtu",
  s2t: "PILIH ITEM ANDA",
  s2d: "Pilih kegemaran anda",
  s3t: "NYATAKAN KUANTITI",
  s3d: "Beritahu kami berapa banyak",
  s4t: "PILIH PENGAMBILAN ATAU PENGHANTARAN",
  s4d: "SG Ara atau Pulau Pinang",
  s5t: "SAHKAN & BUAT BAYARAN",
  s5d: "Pesanan disahkan selepas bayaran ♡",

  iTitle: "PENGAMBILAN & PENGHANTARAN",
  selfTitle: "PENGAMBILAN SENDIRI",
  selfBody: "Kami akan memberitahu anda apabila pesanan sedia untuk diambil.",
  deliTitle: "PENGHANTARAN",
  deliArea: "LALAMOVE — PULAU PINANG",
  deliBody: "Kos penghantaran ditanggung oleh pelanggan. Kami membungkus dengan teliti untuk penghantaran yang selamat.",

  rvTitle: "APA KATA PELANGGAN",
  rvSub: "Ulasan sebenar dari pelanggan sebenar — dialu-alukan dalam Bahasa Inggeris, Mandarin (中文) atau Bahasa Malaysia.",
  rvFormTitle: "TINGGALKAN ULASAN",
  rvNote: "Sudah cuba hasil Jien Luv 2 Bake? Ceritakan pengalaman anda.",
  nameLabel: "Nama anda",
  namePh: "cth. Aisyah",
  ratingLabel: "Penilaian anda",
  rvStarsAria: "Penilaian bintang, 1 hingga 5",
  rvStar1: "1 bintang",
  rvStar2: "2 bintang",
  rvStar3: "3 bintang",
  rvStar4: "4 bintang",
  rvStar5: "5 bintang",
  msgLabel: "Ulasan anda",
  msgPh: "Macam mana bakerinya? Apa yang anda suka?",
  msgNote: "Tulis dalam bahasa yang anda selesa — Inggeris, Mandarin atau Bahasa Malaysia.",
  langLabel: "Bahasa ulasan",
  photoLabel: "Tambah foto (pilihan)",
  photoTake: "Ambil gambar",
  photoChoose: "Pilih foto",
  rvPhotoAlt: "Foto anda",
  rvSubmit: "HANTAR ULASAN",
  rvSending: "Menghantar…",
  rvErrFields: "Sila masukkan nama, penilaian bintang (1–5) dan ulasan ringkas (sehingga 400 aksara).",
  rvTooBig: "Foto itu terlalu besar — sila pilih gambar di bawah 25 MB.",
  rvErrSend: "Ada masalah semasa menghantar ulasan. Sila semak sambungan dan cuba lagi.",
  rvEmpty: "Belum ada ulasan — jadilah yang pertama!",
  rvPrevAria: "Ulasan sebelumnya",
  rvNextAria: "Ulasan seterusnya",
  rvThanksMain: "Terima kasih — ulasan dan foto anda telah sampai kepada pembuat kek. Setiap ulasan dibaca sendiri oleh beliau dan akan dipaparkan di sini sebaik sahaja diluluskan, biasanya dalam satu atau dua hari.",
  rvThanksHonest: "Ulasan yang jujur membantu pelanggan lain memilih dengan baik — terima kasih kerana berkongsi.",

  fConnectTitle: "JOM KITA BERHUBUNG ♡",
  fTag: "Jien Luv 2 Bake<br>Bakar Kecil-Kecilan · Kasih Sayang Yang Besar",
  fWhatsappTitle: "WHATSAPP / TEMPAH",
  fInstaTitle: "IKUTI KAMI DI INSTAGRAM",
  devBy: "Laman web oleh",
};

export const HOME = { en, zh, ms };
