// store-lang.js — the store's (store/) customer-facing strings in English,
// 中文 and Bahasa Malaysia. English values copy the authored copy exactly so a
// visit in English is identical to today. Values may contain a %1 placeholder
// (e.g. the cut-off time) that the caller substitutes at render time.
//
// The order data the baker reads (product names, order lines, the WhatsApp
// message) deliberately stays in the products' English names — only what the
// customer sees on the page is localized.

const en = {
  titleWord: "Order",
  referral: "🎁 You were referred — you have a welcome discount on your first order",
  deliveryDays: "Delivery days",
  orderBy: "Order by",
  beforeVal: "%1 the day before",
  madeToOrder: "Made to order · closes %1 the day before",
  sPickDay: "Pick a delivery day",
  sWhat: "What would you like?",
  sYourDetails: "Your details",
  yourName: "Your name",
  namePh: "e.g. Aunty Bee",
  whatsappNo: "WhatsApp number",
  whatsPh: "e.g. 012-345 6789",
  waSub: "We use this to confirm your order and send your payment QR — we'll never spam you.",
  howGet: "How will you get your order?",
  selfCollect: "Self collect",
  courier: "Courier delivery",
  addressLabel: "Delivery address",
  addressPh: "Street, area, Penang…",
  noteLabel: "Note (optional)",
  notePh: "Allergies, extras, anything…",
  sTrack: "Track your order",
  trackHint: "Placed an order? Enter the order number from your confirmation (it starts with <strong>#</strong>, e.g. #A3F9C2).",
  trackPh: "e.g. A3F9C2",
  trackBtn: "Track",

  items: "%1 items",
  oneItem: "1 item",
  placeOrder: "Place order",
  sending: "Sending…",
  soldOut: "Sold out",
  onlyLeft: "Only %1 left",
  noDates: "No upcoming delivery dates right now — check back soon.",
  noOpenDates: "All upcoming deliveries are full right now — check back soon.",

  confirmAddWaTitle: "Please add your WhatsApp number.",
  confirmAddWaBody: "We use it to confirm your order and send your payment QR.",
  confirmClosedTitle: "That day's orders are closed.",
  confirmClosedBody: "Orders for this day close at %1 the day before — please pick a new delivery day.",
  confirmChangedTitle: "Your order changed just now.",
  confirmChangedBody: "Something sold out while you were ordering — we've fixed your cart to match what's left.",
  confirmChangedSub: "Please review your order and tap Place order again.",
  sendingToBakery: "Sending your order to the bakery…",
  orderRecvTitle: "🎉 Order received!",
  orderRecvBody: "%1 has your order.",
  orderRecvThanksBody: "Thanks %1! %2 has your order.",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "Your order is in with the bakery — we'll WhatsApp you once we confirm it.",
  failTitle: "We couldn't reach the bakery's app just now.",
  failBody: "Don't worry — send your order on WhatsApp so it isn't lost.",
  failOpened: "WhatsApp has opened with your order — press Send so it isn't lost.",
  failLink: "📲 Send your order via WhatsApp",
  failRetry: "Please try again in a moment.",

  trackEnter: "Enter your order number to track it.",
  trackUnavailable: "Tracking isn't available right now.",
  trackLooking: "Looking up your order…",
  trackNotFound: "We couldn't find order #%1. Check the number in your confirmation message — it's the 6 characters after the #.",
  orderCode: "Order #%1",
  forCustomer: "For %1",
  trkNew: "New",
  trkConfirmed: "Confirmed",
  trkPaid: "Paid",
  trkBaking: "Baked",
  trkReady: "Packed",
  trkDelivered: "Delivered",

  devBy: "Website by",
};

const zh = {
  titleWord: "订购",
  referral: "🎁 经由好友推荐 — 首次下单即可享受专属优惠",
  deliveryDays: "派送日",
  orderBy: "下单截止",
  beforeVal: "烘焙日前一天 %1 前",
  madeToOrder: "按订单新鲜制作 · %1 截单（烘焙日前一天）",
  sPickDay: "选择派送日",
  sWhat: "想吃什么？",
  sYourDetails: "你的资料",
  yourName: "你的名字",
  namePh: "例如：Aunty Bee",
  whatsappNo: "WhatsApp 号码",
  whatsPh: "例如：012-345 6789",
  waSub: "我们会用这个号码确认订单并发送付款二维码，绝不会骚扰你。",
  howGet: "你希望怎样取货？",
  selfCollect: "自取",
  courier: "外送",
  addressLabel: "派送地址",
  addressPh: "街道、区域、槟城…",
  noteLabel: "备注（可选）",
  notePh: "过敏原、额外要求、其它…",
  sTrack: "查询订单",
  trackHint: "已经下单了？请输入确认讯息里的订单编号（以 <strong>#</strong> 开头，例如 #A3F9C2）。",
  trackPh: "例如：A3F9C2",
  trackBtn: "查询",

  items: "%1 项",
  oneItem: "1 项",
  placeOrder: "提交订单",
  sending: "发送中…",
  soldOut: "已售完",
  onlyLeft: "仅剩 %1 份",
  noDates: "目前没有可预订的派送日 — 请稍后再来。",
  noOpenDates: "近期派送均已满 — 请稍后再来。",

  confirmAddWaTitle: "请填写你的 WhatsApp 号码。",
  confirmAddWaBody: "我们会用它确认订单并发送付款二维码。",
  confirmClosedTitle: "该日的订单已截止。",
  confirmClosedBody: "此日的订单需在烘焙日前一天 %1 前下单 — 请另选一个派送日。",
  confirmChangedTitle: "你的订单刚刚有变动。",
  confirmChangedBody: "下单期间有商品售完了 — 我们已根据剩余数量更新你的购物车。",
  confirmChangedSub: "请确认后再按「提交订单」。",
  sendingToBakery: "正在把你的订单发送给烘焙师…",
  orderRecvTitle: "🎉 订单已收到！",
  orderRecvBody: "%1 已收到你的订单。",
  orderRecvThanksBody: "谢谢 %1！%2 已收到你的订单。",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "订单已送达烘焙师 — 确认后我们会通过 WhatsApp 通知你。",
  failTitle: "暂时联系不上烘焙店。",
  failBody: "别担心 — 请通过 WhatsApp 发送订单，以免遗漏。",
  failOpened: "WhatsApp 已打开并带上你的订单 — 请按「发送」。",
  failLink: "📲 通过 WhatsApp 发送订单",
  failRetry: "请稍后再试一次。",

  trackEnter: "请输入订单编号查询。",
  trackUnavailable: "现在暂时无法查询。",
  trackLooking: "正在查询你的订单…",
  trackNotFound: "找不到订单 #%1。请检查确认讯息中的编号 — 即 # 号后的 6 个字符。",
  orderCode: "订单 #%1",
  forCustomer: "顾客：%1",
  trkNew: "新订单",
  trkConfirmed: "已确认",
  trkPaid: "已付款",
  trkBaking: "烘焙中",
  trkReady: "已打包",
  trkDelivered: "已送达",

  devBy: "网站制作：",
};

const ms = {
  titleWord: "Tempahan",
  referral: "🎁 Anda dirujuk — anda ada diskaun sambutan untuk tempahan pertama",
  deliveryDays: "Hari penghantaran",
  orderBy: "Tempahan ditutup",
  beforeVal: "%1 sehari sebelumnya",
  madeToOrder: "Dibuat mengikut tempahan · tutup %1 sehari sebelum",
  sPickDay: "Pilih hari penghantaran",
  sWhat: "Apa yang anda mahu?",
  sYourDetails: "Maklumat anda",
  yourName: "Nama anda",
  namePh: "cth. Aunty Bee",
  whatsappNo: "Nombor WhatsApp",
  whatsPh: "cth. 012-345 6789",
  waSub: "Kami guna nombor ini untuk sahkan tempahan dan hantar QR pembayaran — kami tidak akan spam anda.",
  howGet: "Macam mana anda mahu ambil tempahan?",
  selfCollect: "Ambil sendiri",
  courier: "Penghantaran kurier",
  addressLabel: "Alamat penghantaran",
  addressPh: "Jalan, kawasan, Pulau Pinang…",
  noteLabel: "Nota (pilihan)",
  notePh: "Alahan, tambahan, apa-apa sahaja…",
  sTrack: "Semak tempahan anda",
  trackHint: "Sudah menempah? Masukkan nombor tempahan dari mesej pengesahan (bermula dengan <strong>#</strong>, cth. #A3F9C2).",
  trackPh: "cth. A3F9C2",
  trackBtn: "Semak",

  items: "%1 item",
  oneItem: "1 item",
  placeOrder: "Hantar tempahan",
  sending: "Menghantar…",
  soldOut: "Habis",
  onlyLeft: "Tinggal %1 sahaja",
  noDates: "Tiada tarikh penghantaran buat masa ini — sila datang lagi nanti.",
  noOpenDates: "Semua penghantaran akan datang penuh buat masa ini — sila datang lagi nanti.",

  confirmAddWaTitle: "Sila masukkan nombor WhatsApp anda.",
  confirmAddWaBody: "Kami guna untuk sahkan tempahan dan hantar QR pembayaran anda.",
  confirmClosedTitle: "Tempahan untuk hari itu sudah ditutup.",
  confirmClosedBody: "Tempahan untuk hari ini ditutup pada %1 sehari sebelum — sila pilih hari penghantaran baharu.",
  confirmChangedTitle: "Tempahan anda baru sahaja berubah.",
  confirmChangedBody: "Ada barang yang habis semasa anda menempah — kami telah kemas kini troli anda mengikut apa yang tinggal.",
  confirmChangedSub: "Sila semak tempahan anda dan tekan Hantar tempahan sekali lagi.",
  sendingToBakery: "Menghantar tempahan anda kepada pembuat kek…",
  orderRecvTitle: "🎉 Tempahan diterima!",
  orderRecvBody: "%1 telah menerima tempahan anda.",
  orderRecvThanksBody: "Terima kasih %1! %2 telah menerima tempahan anda.",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "Tempahan anda telah sampai kepada pembuat kek — kami akan WhatsApp anda sebaik sahaja disahkan.",
  failTitle: "Kami tidak dapat menghubungi aplikasi kedai buat masa ini.",
  failBody: "Jangan risau — hantar tempahan anda melalui WhatsApp supaya ia tidak hilang.",
  failOpened: "WhatsApp telah dibuka dengan tempahan anda — tekan Hantar supaya ia tidak hilang.",
  failLink: "📲 Hantar tempahan anda melalui WhatsApp",
  failRetry: "Sila cuba lagi sebentar lagi.",

  trackEnter: "Masukkan nombor tempahan anda untuk disemak.",
  trackUnavailable: "Semakan tidak tersedia buat masa ini.",
  trackLooking: "Mencari tempahan anda…",
  trackNotFound: "Kami tidak dapat mencari tempahan #%1. Sila semak nombor dalam mesej pengesahan anda — iaitu 6 aksara selepas #.",
  orderCode: "Tempahan #%1",
  forCustomer: "Untuk %1",
  trkNew: "Baharu",
  trkConfirmed: "Disahkan",
  trkPaid: "Dibayar",
  trkBaking: "Dibakar",
  trkReady: "Dibungkus",
  trkDelivered: "Dihantar",

  devBy: "Laman web oleh",
};

export const STORE = { en, zh, ms };
